version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: hub
    ports: 
      - "3000:3000"
    depends_on:
      - db
    network_mode: host
    privileged: true

  db:
    image: jsurf/rpi-mariadb
    restart: always
    container_name: maria

    volumes:
      - ./docker/data:/var/lib/maria/data
      - ./sql-scripts:docker-entrypoint-initdb.d

    #healthcheck를 통해 db컨테이너가 제대로 실행되는지 체크
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=user --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=hub_system
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
